### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by zedream** [view-design/view-ui-project-nuxt#1]
Nuxt CLI v3.0.0-rc.3                                                                                          11:07:54
                                                                                                              11:07:54
  > Local:    http://localhost:3000/
  > Network:  http://192.168.204.174:3000/

i Vite server warmed up in 1205ms                                                                             11:08:06
i Vite client warmed up in 4981ms                                                                             11:08:06
√ Vite server built in 3622ms                                                                                 11:08:09
√ Nitro built in 463 ms                                                                                 nitro 11:08:09
ReferenceError: document is not defined
    at E:\view-ui-project-nuxt\node_modules\view-ui-plus\dist\viewuiplus.min.js:1:752
    at E:\view-ui-project-nuxt\node_modules\view-ui-plus\dist\viewuiplus.min.js:1:892
    at E:\view-ui-project-nuxt\node_modules\view-ui-plus\dist\viewuiplus.min.js:1:527
    at Object.<anonymous> (E:\view-ui-project-nuxt\node_modules\view-ui-plus\dist\viewuiplus.min.js:1:699)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)

**Comment by zedream** [comment]
> Nuxt CLI v3.0.0-rc.3 11:07:54 11:07:54
> 
> > Local:    http://localhost:3000/
> > Network:  http://192.168.204.174:3000/
> 
> i Vite server warmed up in 1205ms 11:08:06 i Vite client warmed up in 4981ms 11:08:06 √ Vite server built in 3622ms 11:08:09 √ Nitro built in 463 ms nitro 11:08:09 ReferenceError: document is not defined at E:\view-ui-project-nuxt\node_modules\view-ui-plus\dist\viewuiplus.min.js:1:752 at E:\view-ui-project-nuxt\node_modules\view-ui-plus\dist\viewuiplus.min.js:1:892 at E:\view-ui-project-nuxt\node_modules\view-ui-plus\dist\viewuiplus.min.js:1:527 at Object. (E:\view-ui-project-nuxt\node_modules\view-ui-plus\dist\viewuiplus.min.js:1:699) at Module._compile (node:internal/modules/cjs/loader:1105:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10) at Module.load (node:internal/modules/cjs/loader:981:32) at Function.Module._load (node:internal/modules/cjs/loader:822:12) at ModuleWrap. (node:internal/modules/esm/translators:170:29) at ModuleJob.run (node:internal/modules/esm/module_job:198:25)

**Comment by zedream** [comment]
node: v16.15.0
npm: v8.5.5
